// Regenerates the ABIs and the vault creation bytecode the web app ships with.
//   node contracts/script/gen-abi.mjs      (after `forge build`)
// Hand-editing the output is how an ABI drifts from the bytecode it describes.
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const OUT = join(import.meta.dirname, "..", "out");
const WEB = join(import.meta.dirname, "..", "..", "web", "src", "lib", "chain");

const artifact = (file, name) =>
  JSON.parse(readFileSync(join(OUT, file, `${name}.json`), "utf8"));

/** Views and writes the app actually calls, so the bundle carries nothing dead. */
const keep = (abi, names) =>
  abi.filter((entry) => entry.type === "function" && names.includes(entry.name));

const header =
  "// Generated by contracts/script/gen-abi.mjs from `forge build` output.\n" +
  "// Do not hand-edit: regenerate it so the ABIs can never drift from the\n" +
  "// bytecode they describe.\n";

const ts = (name, value) =>
  `export const ${name} = ${JSON.stringify(value, null, 2)} as const;\n`;

const registry = artifact("SBot3Registry.sol", "SBot3Registry");
const vault = artifact("IndexVault.sol", "IndexVault");
const book = artifact("TokenBook.sol", "TokenBook");
const mock = artifact("MockERC20.sol", "MockERC20");

writeFileSync(
  join(WEB, "abi.ts"),
  header +
    "\n" +
    ts(
      "sbot3RegistryAbi",
      keep(registry.abi, [
        "create",
        "lock",
        "setMethodology",
        "delegate",
        "setVault",
        "setWeights",
        "getIndex",
        "weightsOf",
        "symbolsOf",
        "weightOf",
        "exists",
        "isLocked",
        "vaultOf",
        "allLabels",
        "totalIndexes",
        "MAX_CONSTITUENTS",
      ]),
    ) +
    "\n" +
    ts(
      "tokenBookAbi",
      keep(book.abi, ["register", "addressOf", "addressesOf", "isRegistered", "allSymbols"]),
    ),
);

writeFileSync(
  join(WEB, "vault.ts"),
  header +
    "\n" +
    ts(
      "indexVaultAbi",
      keep(vault.abi, [
        "label",
        "tokens",
        "unitPrices",
        "constituents",
        "weights",
        "holdings",
        "totalNotional",
        "navPerShare",
        "driftBps",
        "previewSubscribe",
        "previewRedeem",
        "subscribe",
        "redeem",
        "feeBps",
        "ownerFeeBps",
        "feeRecipient",
        "seedNav",
        "balanceOf",
        "totalSupply",
      ]),
    ) +
    "\n" +
    ts(
      "mockErc20Abi",
      keep(mock.abi, [
        "allowance",
        "approve",
        "balanceOf",
        "decimals",
        "faucet",
        "faucetAmount",
        "mint",
        "symbol",
        "name",
      ]),
    ) +
    `
/** Shares are always 18 decimals, and so is the unit of account. */
export const SHARE_DECIMALS = 18;
export const NOTIONAL_DECIMALS = 18;

/** Basis points, as the contracts count them. */
export const TOTAL_BPS = 10_000;

/**
 * Creation bytecode for IndexVault, so an index owner can deploy the vault that
 * settles their own index straight from the browser.
 */
export const indexVaultBytecode =
  ${JSON.stringify(vault.bytecode.object)} as \`0x\${string}\`;

` +
    ts(
      "indexVaultConstructorAbi",
      vault.abi.filter((entry) => entry.type === "constructor"),
    ),
);

/**
 * Formatted here rather than left to the author, so regenerating never leaves
 * `pnpm lint` failing on two files nobody is supposed to hand-edit.
 */
execFileSync(
  "pnpm",
  ["exec", "biome", "check", "--write", "src/lib/chain/abi.ts", "src/lib/chain/vault.ts"],
  { cwd: join(import.meta.dirname, "..", "..", "web"), stdio: "ignore" },
);

console.log("Wrote abi.ts and vault.ts");
